{% set name = "pyraphtory" %}
{% set version = "v0.2.0.alpha" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.haaroonyousaf.com/files/makefile-remove-ctl-seq.tar.gz
  sha256: 97fd78184e87c19258396ced7c9d0f115ee4d07e8edc80d86b2b471639f4051e


build:
  skip: true  # [not unix]
  number: {{ build_number }}

requirements:
  host:
    - make
    - git
    - openjdk ==11.0.15
    - python ==3.9.13
    - python-build
    - poetry
    - pip
    - sbt
    - setuptools
    - six
  run:
    - make
    - openjdk ==11.0.15
    - python ==3.9.13
    - sbt
    - six

test:
  imports:
    - pyraphtory

about:
  home: https://github.com/raphtory/raphtory/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Raphtory python API, Temporal Graph analytics
  doc_url: https://docs.raphtory.com/
  dev_url: https://github.com/raphtory/raphtory


extra:
  recipe-maintainers:
    - Pometry-Team
    - haaroon
    - ljeub-pometry
    - miratepuffin
    - jamesalford
    
