{% set name = "pemja" %}
{% set version = "0.2.5" %}
{% set build_number = "0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff4e8fb432782bc563575685d49dff6465ea5405f320335bb77a272feb681e83

build:
  skip: true  # [not unix]
  number: {{ build_number }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "


requirements:
  host:
    - gcc
    - git
    - maven
    - openjdk ==11.0.15
    - python ==3.9.13
    - numpy ==1.21.4
    - pip
    - python-build
  run:
    - python ==3.9.13
    - openjdk ==11.0.15
    - numpy ==1.21.4


test:
  imports:
    - pemja
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pemja/
  summary: PemJa is an open source cross language call framework based on FFI. It aims to provide a high-performance framework of calling between different languages.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/alibaba/pemja
  dev_url: https://github.com/alibaba/pemja


extra:
  recipe-maintainers:
    - HuangXingBo
